name: week5hw

services:
  api:
    build: ./api
    image: week5_03
    container_name: week5_api02
    environment:
      DATA_DIR: /data
    volumes:
      - data:/data

  nginx:
    build: ./nginx
    image: week5_04
    container_name: week5_web02
    ports:
      - "8080:80"
    depends_on:
      - api

networks:
  default:
    name: week5_net02

volumes:
  data:
    name: week5_data02